# Generated by Django 4.2.7 on 2023-12-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='содержание'),
        ),
    ]
